### ISSUE TITLE
Make `box.rb` the canonical build filename

### ISSUE THREAD

**Issue by erikh** [box-builder/box#194]
@errordeveloper started doing this and I think it's a great idea. `box` should always be able to accept an unknown command as a filename, but I think `box`, without args, should run a `Boxfile`.

WDYT? Comments appreciated.

**Comment by Xe** [comment]
If you call it `box.rb`, people won't have to add editor modelines or special rules to use ruby formatting for that buffer.

**Comment by erikh** [comment]
Yeah, that's a really good point. What do you think @errordeveloper?

On Tue, Mar 14, 2017 at 8:34 AM, Christine Dodrill <notifications@github.com

**Comment by errordeveloper** [comment]
It's true about syntax highlighting, but I like `Boxfile` cause then it is in the league of `Makefile`, `Gemfile`, `Profile`, `Dockerfile` etc. But on the other had, consider something like Github's language stats and search, should it really fall into Ruby bucket or is it a language of its own? There is a `Dockerfile` bucket in Github search and stats too (IIRC), but `Gemfile` falls into the Ruby bucket.

**Comment by erikh** [comment]
well I mean it's just ruby, but yeah, it doesn't really use the ruby
standard library or even many parts of the core library. That said, github
vs. editor support is an easy pick for me, especially because we'll still
get the highlighting for both. Also, with the low popularity of box so far,
they may not even accept a proposal like this.

However, Boxfile is nice because it advertises the project a little. Let me
mull over this and I'll make a decision.

I've been using `build.rb`, fwiw.

**Comment by erikh** [comment]
I'm going to go with box.rb; I've adjusted the title and will start making the changes before 0.6.0.

**Comment by cmaujean** [comment]
latest pr on this is #236
